namespace: smb-workload
imagePullSecrets: registry-github
frontend:
  name: frontend
  image: ghcr.io/patiphannew/int365-client:dev
  port: 80
backend:
  name: backend
  image: ghcr.io/patiphannew/int365-backend:dev
  port: 3000
ingress:
  name: ingressctl
  host: jaid.ddns.net
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  frontend:
    path: /?(.*)
  backend:
    path: /backend/?(.*)
