apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: smb-workload
data:
  nginx.conf: |
   events {
        worker_connections  1024;
   }
   http {
    server {
      listen       80;
      server_name  jaid.ddns.net;
      root         /usr/share/nginx/html;
      location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://frontend-svc;
      }
      location /backend/ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://backend-svc/;
      }
    }
   }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: smb-workload
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-custom
  namespace: smb-workload
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx


